name: Lua

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .config/nvim/**

jobs:
  lint:
    runs-on: ci_runner
    steps:
      - uses: actions/checkout/@v6
      - name: Install stylua
        env:
          # As of release-gitter 3.2, this will try to send the GITHUB_TOKEN as
          # part of the request. In my forgejo this maps to a FORGEJO_TOKEN,
          # which gets rejected with 401.
          GITHUB_TOKEN: ""
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install git+https://github.com/johnnymorganz/stylua
      - name: Run stylua
        run: |
          set -e
          source venv/bin/activate
          stylua .config/nvim --check --verbose --color Always
