git:
  pagers:
    - colorArg: always
      pager: diff-so-fancy
  autoFetch: false
# Use exit with esc key instead of ctrl-c
quitOnTopLevelReturn: true
# TODO: Figure out a better way to use multiple nvim sessions with sockets
# os:
#   edit: 'nvim --server /tmp/nvimsocket --remote-tab {{filename}}'
gui:
  nerdFontsVersion: "3"
